import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import XLSX from 'xlsx';import {KINDS,HEADERS} from '../lib/posting-core.js';
test('Apps Script roundtrip updates the same XLSX, retains PDFs/photos, retries safely, and moves photos',()=>{
 const MASTER='12e7bfzCiv9M3NpPOQmdtd6r75QZj9g98',ROOT='1FVpx-2alioghme97E-sqGIe8vNdg63Fu';let wb=XLSX.utils.book_new();for(const k of KINDS)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([HEADERS]),k);
 let bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),creates=0,locked=false;const files=new Map();
 const parents=()=>{let next=true;return {hasNext:()=>next,next:()=>{next=false;return {getId:()=>ROOT};}};};
 const ctx={XLSX,Uint8Array,Date,console,PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'secret'})},LockService:{getScriptLock:()=>({tryLock:()=>{locked=true;return true;},hasLock:()=>locked,releaseLock:()=>{locked=false;}})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})},ScriptApp:{getOAuthToken:()=> 'test-token'},Utilities:{base64Decode:s=>Array.from(Buffer.from(s,'base64')),newBlob:(b,t,n)=>({b,t,n})},DriveApp:{getFileById:id=>{assert.equal(id,MASTER);return {getParents:parents,getBlob:()=>({getBytes:()=>Array.from(bytes)})};},getFolderById:id=>({getParents:parents,getFilesByName:name=>({hasNext:()=>files.has(id+name),next:()=>files.get(id+name)}),createFile:blob=>{creates++;const f={getId:()=> 'asset-'+creates,getUrl:()=> 'https://drive.test/asset-'+creates};files.set(id+blob.n,f);return f;}})},UrlFetchApp:{fetch:(url,options)=>{assert.ok(url.includes(MASTER));assert.equal(options.method,'patch');bytes=Buffer.from(options.payload);return {getResponseCode:()=>200};}}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('lib/posting-core.js','utf8').replace(/export /g,'')+'\n'+fs.readFileSync('google-apps-script/Service.js','utf8'),ctx);
 const request=x=>ctx.doPost({postData:{contents:JSON.stringify({...x,posting:true,secret:'secret'})}});
 const base={action:'save',id:'test-row-00001',kind:KINDS[0],title:'ทดสอบจ้างตรวจ MRI',postedDate:'2026-10-08',requestId:'request-one'};
 let result=request({...base,pdfUpload:{key:'asset-pdf-0000001',name:'test.pdf',type:'application/pdf',base64:'YWJj'},photoUploads:[{key:'asset-photo-00001',name:'one.png',type:'image/png',base64:'YWJj'},{key:'asset-photo-00002',name:'two.png',type:'image/png',base64:'YWJj'}]});assert.equal(result.error,undefined);assert.equal(result.row.photos.length,2);assert.equal(result.row.sequence,1);assert.equal(creates,3);
 assert.equal(request(base).row.revision,1);assert.equal(creates,3);assert.equal(request({action:'list'}).rows.length,1);
 const second=request({...base,id:'test-row-00002',requestId:'request-two'});assert.equal(second.row.sequence,2);
 result=request({action:'movePhoto',id:base.id,revision:1,targetId:second.row.id,targetRevision:1,photoId:'asset-2',requestId:'move-one'});assert.equal(result.error,undefined);const rows=request({action:'list'}).rows;assert.equal(rows[0].photos.length,1);assert.equal(rows[1].photos.length,1);
 assert.equal(request({...base,revision:1,requestId:'stale'}).error.includes('เครื่องอื่น'),true);
 const reread=XLSX.read(bytes);assert.deepEqual(reread.SheetNames,KINDS);const sheet=XLSX.utils.sheet_to_json(reread.Sheets[KINDS[0]]);assert.equal(sheet.length,2);assert.ok(sheet.some(r=>r['ลิงก์ PDF ใน Drive'].includes('asset-1')));assert.equal(locked,false);
});
