"use client";
import {useEffect,useMemo,useState} from 'react';
import type {PostingRow,Asset} from '../../lib/posting-media';
import {dailyGroups,dailyId,appendNotes,uploadBatches,photoThumbnail,photoDownload} from '../../lib/posting-daily.js';
import webEvidence from '../../lib/posting-web-evidence.json';
type Pending={file:File;key:string;preview:string};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const thaiDate=(date:string)=>new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Bangkok'}).format(new Date(date+'T12:00:00+07:00'));
const photoTypes=/^image\/(jpeg|png|webp|heic|heif)$/;
async function upload(item:Pending){const type=item.file.type||(/\.hei[cf]$/i.test(item.file.name)?'image/heic':'');if(!photoTypes.test(type))throw Error('รองรับรูป JPG, PNG, WebP และ HEIC');return {key:item.key,name:item.file.name,type,base64:await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('อ่านรูปไม่สำเร็จ'));reader.readAsDataURL(item.file);})};}
function EvidencePhoto({photo,index}:{photo:Asset;index:number}){const [failed,setFailed]=useState(false);return <figure className="evidence-photo"><a href={photo.url} target="_blank" rel="noreferrer" aria-label={'ดูรูป '+(index+1)}>{failed?<span className="photo-fallback">📷 รูป {index+1}<small>เปิดดูใน Google Drive</small></span>:<img src={photoThumbnail(photo)} alt={'หลักฐานรูป '+(index+1)} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>}</a><figcaption><span>รูป {index+1}</span><a href={photo.url} target="_blank" rel="noreferrer">ดูรูปใหญ่</a><a href={photoDownload(photo)} target="_blank" rel="noreferrer">ดาวน์โหลดต้นฉบับ</a></figcaption></figure>;}
export default function DailyEvidence(){
 const [code,setCode]=useState(''),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[rows,setRows]=useState<PostingRow[]>([]),[date,setDate]=useState(today),[notes,setNotes]=useState(''),[pending,setPending]=useState<Pending[]>([]),[message,setMessage]=useState('ใส่รหัสเจ้าหน้าที่เดิมแล้วเชื่อม Google Drive เพื่อเริ่มบันทึก'),[open,setOpen]=useState<Record<string,boolean>>({});
 const groups=useMemo(()=>{
  const displayRows=rows.map(row=>({...row,photos:(row.photos||[]).map(photo=>{const original=webEvidence.find(day=>day.date===row.postedDate)?.photos.find(p=>p.name===photo.name);return original?{...photo,url:original.url}:photo;})}));
  const previews=webEvidence.map(day=>({id:'web-evidence-'+day.date,postedDate:day.date,title:'หลักฐานการติดประกาศรายวัน',notes:'',photos:day.photos.filter(photo=>!rows.some(row=>row.postedDate===day.date&&(row.photos||[]).some(p=>p.name===photo.name)))}));
  return dailyGroups([...displayRows,...previews]);
 },[rows]);
 async function api(body?:unknown,access=code){if(!access.trim())throw Error('กรุณาใส่รหัสเจ้าหน้าที่เดิม');const response=await fetch('/api/posting',{method:body?'POST':'GET',cache:'no-store',signal:AbortSignal.timeout(120000),headers:{'Content-Type':'application/json','X-Posting-Code':access.trim()},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json().catch(()=>({error:'บริการตอบกลับไม่ถูกต้อง กรุณาลองใหม่'}));if(response.status===401){setConnected(false);try{sessionStorage.removeItem('posting-access');}catch{}}if(!response.ok||data.error)throw Error(data.error||'เชื่อม Google Drive ไม่สำเร็จ');return data;}
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function connect(access=code){setMessage('กำลังเชื่อม Google Drive เดิม กรุณารอสักครู่');const data=await api(undefined,access);if(!Array.isArray(data.rows))throw Error('โหลดข้อมูลจาก Master เดิมไม่สำเร็จ');setRows(data.rows);setConnected(true);try{sessionStorage.setItem('posting-access',access.trim());}catch{}setMessage('เชื่อม Google Drive เดิมแล้ว พร้อมบันทึกรูปตามวันที่');}
 useEffect(()=>{try{const saved=sessionStorage.getItem('posting-access');if(saved){setCode(saved);void run(()=>connect(saved));}}catch{}},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(pending.length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[pending.length]);
 function choose(files:File[]){try{for(const file of files){if(file.size>20*1024*1024)throw Error('รูปแต่ละไฟล์ต้องไม่เกิน 20 MB');if(!photoTypes.test(file.type||(/\.hei[cf]$/i.test(file.name)?'image/heic':'')))throw Error('รองรับรูป JPG, PNG, WebP และ HEIC');}setPending(prev=>[...prev,...files.map(file=>({file,key:crypto.randomUUID(),preview:URL.createObjectURL(file)}))]);setMessage('เลือกรูปแล้ว กดบันทึกรูปของวันนี้เพื่อเก็บใน Google Drive');}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 const save=()=>run(async()=>{
  if(!date||!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date).toISOString().slice(0,10)!==date)throw Error('เลือกวันที่ติดประกาศให้ถูกต้อง');if(!pending.length)throw Error('เลือกรูปอย่างน้อยหนึ่งรูป');
  const selectedDate=date,selectedNotes=notes,batches=uploadBatches(pending);const data=await api();if(!Array.isArray(data.rows))throw Error('โหลดข้อมูลก่อนบันทึกไม่สำเร็จ');let latest:PostingRow[]=data.rows;setRows(latest);
  for(let i=0;i<batches.length;i++){const batch:Pending[]=batches[i];setMessage(`กำลังบันทึกรูป ${i+1}/${batches.length} ชุด กรุณารอสักครู่`);const existing=latest.find(r=>r.id===dailyId(selectedDate));const body={...(existing||{id:dailyId(selectedDate),revision:0,kind:'ประกาศประกวดราคา',title:'หลักฐานการติดประกาศวันที่ '+thaiDate(selectedDate),postedDate:selectedDate}),action:'save',requestId:'daily-'+batch[0].key,notes:appendNotes(existing?.notes,selectedNotes),photoUploads:await Promise.all(batch.map(upload))};const result=await api(body);const saved:PostingRow=result.row;if(!saved||saved.postedDate!==selectedDate||!batch.every(item=>saved.photos?.some(p=>(p as Asset&{key?:string}).key===item.key)))throw Error('ยังยืนยันรูปใน Master ไม่ครบ กรุณากดบันทึกอีกครั้ง รูปเดิมจะไม่ซ้ำ');latest=[saved,...latest.filter(r=>r.id!==saved.id)];setRows(latest);const keys=new Set(batch.map(item=>item.key));setPending(prev=>prev.filter(item=>!keys.has(item.key)));batch.forEach(item=>URL.revokeObjectURL(item.preview));}
  setNotes('');setOpen(prev=>({...prev,[selectedDate]:true}));setMessage('บันทึกรูปลง Google Drive และตรวจอ่านกลับจาก Master เดิมสำเร็จ');
 });
 return <main className="daily-evidence"><style>{`.daily-evidence{min-height:100vh;background:#f1f7fc;color:#16304f;font-family:system-ui,sans-serif}.daily-evidence header{background:linear-gradient(110deg,#dff4ff,#fff,#dff8ef);padding:20px;border-bottom:1px solid #cfe8f5}.daily-evidence h1{font-size:clamp(22px,4vw,30px);margin:0 0 6px}.daily-evidence .content{max-width:1060px;padding:16px;margin:auto}.daily-evidence section{background:white;border:1px solid #dbeafe;border-radius:14px;padding:18px;margin-bottom:16px}.daily-evidence input,.daily-evidence textarea,.daily-evidence button{font:inherit;border:1px solid #b9cee5;border-radius:8px;padding:10px;max-width:100%;box-sizing:border-box}.daily-evidence button{cursor:pointer;background:#eaf3ff;color:#16304f}.daily-evidence button:disabled{opacity:.5;cursor:not-allowed}.daily-evidence a{color:#1769c2}.daily-evidence .connection{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.daily-evidence .form{display:grid;gap:16px}.daily-evidence .form label{display:grid;gap:6px;font-weight:600}.daily-evidence .save{background:#1769c2;color:white;font-weight:700}.daily-evidence .photos{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,320px),1fr));gap:12px}.daily-evidence figure{margin:0;border:1px solid #dbeafe;border-radius:10px;overflow:hidden}.daily-evidence figure img{width:100%;height:auto;object-fit:contain;display:block}.daily-evidence figcaption{display:flex;gap:8px;flex-wrap:wrap;padding:10px;font-size:13px}.daily-evidence .day-title{width:100%;text-align:left;background:#f4f8ff;font-weight:700;font-size:18px}.daily-evidence .day-tools{display:flex;gap:8px;margin:10px 0;flex-wrap:wrap}.daily-evidence small{display:block;color:#64748b}.daily-evidence .photo-fallback{height:180px;display:grid;place-content:center;text-align:center;background:#eef4fa}.daily-evidence .pending img{height:auto;object-fit:contain}.daily-evidence .note{white-space:pre-wrap;font-size:14px}`}</style>
 <header><div style={{maxWidth:1060,margin:'auto'}}><h1>📷 หลักฐานการติดประกาศรายวัน</h1><div>กลุ่มงานพัสดุ โรงพยาบาลอุตรดิตถ์</div><a href="/">🏠 กลับหน้าหลัก</a></div></header>
 <div className="content"><section><div className="connection"><input type="password" aria-label="รหัสเจ้าหน้าที่" placeholder="รหัสเจ้าหน้าที่เดิม" value={code} disabled={busy} onChange={e=>{setCode(e.target.value);setConnected(false);}} onKeyDown={e=>{if(e.key==='Enter'&&!busy)void run(()=>connect());}}/><button disabled={busy} onClick={()=>run(()=>connect())}>เชื่อม / โหลดข้อมูล Google Drive</button></div><p role="status" aria-live="polite">{busy?'⏳ ':''}{message}</p></section>
 <section className="form"><label>วันที่ติดประกาศ:<input aria-label="วันที่ติดประกาศ" type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><label>อัปโหลดรูปหลักฐาน:<input aria-label="อัปโหลดรูปหลักฐาน" type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif" disabled={false} onChange={e=>{choose(Array.from(e.target.files||[]));e.target.value='';}}/></label><small>เลือกหลายรูปพร้อมกันได้ เพิ่มรูปในวันเดิมได้โดยเก็บรูปเก่าไว้</small><label>หมายเหตุ: <small>ไม่บังคับ</small><textarea aria-label="หมายเหตุ" rows={3} value={notes} disabled={busy} onChange={e=>setNotes(e.target.value)}/></label>
 {pending.length>0&&<div><b>รอบันทึก {pending.length} รูป · {date?thaiDate(date):'เลือกวันที่'}</b><div className="photos pending">{pending.map(item=><figure key={item.key}><a href={item.preview} target="_blank" rel="noreferrer" aria-label={"ดูรูป "+item.file.name}><img src={item.preview} alt={item.file.name}/></a><figcaption><span>{item.file.name}</span><a href={item.preview} download={item.file.name}>ดาวน์โหลดต้นฉบับ</a><button disabled={busy} onClick={()=>{setPending(prev=>prev.filter(p=>p.key!==item.key));URL.revokeObjectURL(item.preview);}}>นำออก</button></figcaption></figure>)}</div></div>}<button className="save" disabled={busy} onClick={save}>บันทึกรูปของวันนี้</button></section>
 <h2 style={{fontSize:22}}>หลักฐานย้อนหลังตามวันที่</h2>{groups.map(group=><section key={group.date}><button className="day-title" aria-expanded={!!open[group.date]} onClick={()=>setOpen(prev=>({...prev,[group.date]:!prev[group.date]}))}>📅 ติดประกาศวันที่ {thaiDate(group.date)} {open[group.date]?'▴':'▾'}</button><p>รูปทั้งหมด {group.photos.length} รูป</p><div className="day-tools"><button onClick={()=>setOpen(prev=>({...prev,[group.date]:true}))}>ดูรูป</button><button onClick={()=>setOpen(prev=>({...prev,[group.date]:true}))}>ดาวน์โหลดรูป</button><button disabled={busy} onClick={()=>{setDate(group.date);setOpen(prev=>({...prev,[group.date]:true}));setMessage('เลือกวันที่เดิมแล้ว เลือกรูปเพิ่มเติมและกดบันทึกได้');}}>เพิ่มรูปในวันนี้</button></div>{open[group.date]&&<><div className="photos">{group.photos.map((photo,index)=><EvidencePhoto key={photo.id||photo.url} photo={photo as Asset} index={index}/>)}</div>{group.notes.length>0&&<p className="note">หมายเหตุ: {group.notes.join('\n')}</p>}</>}</section>)}{connected&&!groups.length&&<section>ยังไม่มีรูปหลักฐานที่บันทึกไว้ เลือกวันที่และรูปด้านบนเพื่อเริ่มบันทึก</section>}</div></main>;
}
