"use client";
import {useEffect,useMemo,useState} from 'react';
import {KINDS,exactMatch,suggest,validateRanges} from '../../lib/posting-core.js';
import {readImage,readPdf,splitPdf,uploadData,type PostingRow,type Part} from '../../lib/posting-media';
type Draft=PostingRow & {pdfFile?:File;photoFiles?:File[];keepPhotoIds?:string[];requestId?:string};
type Photo={file:File;text:string;target:string;preview:string};
const card={background:'#fff',border:'1px solid #dbeafe',borderRadius:14,padding:14,marginBottom:12};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fresh=(kind:string,date:string):Draft=>({id:crypto.randomUUID(),sequence:0,title:'',kind,postedDate:date,notes:'',revision:0,pdf:null,photos:[]});
export default function PostingPage(){
 const [rows,setRows]=useState<PostingRow[]>([]),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[code,setCode]=useState(''),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('ใส่รหัสเข้าใช้งาน แล้วกดเชื่อม / โหลดข้อมูล Google Drive เพื่อปลดล็อกการบันทึกและอัปโหลด'),[kind,setKind]=useState('ทั้งหมด'),[date,setDate]=useState(''),[workDate,setWorkDate]=useState(today),[q,setQ]=useState(''),[pdf,setPdf]=useState<File|null>(null),[parts,setParts]=useState<Part[]>([]),[total,setTotal]=useState(0),[photos,setPhotos]=useState<Photo[]>([]);
 const activeKind=kind==='ทั้งหมด'?KINDS[0]:kind;
 const [pdfPreview,setPdfPreview]=useState('');
 useEffect(()=>{if(!pdf){setPdfPreview('');return;}const url=URL.createObjectURL(pdf);setPdfPreview(url);return ()=>URL.revokeObjectURL(url);},[pdf]);
 const api=async(body?:unknown,access=code)=>{if(!access.trim())throw Error('ใส่รหัสเข้าใช้งานด้านบน แล้วกดเชื่อม / โหลดข้อมูล Google Drive ก่อน');const res=await fetch('/api/posting',{method:body?'POST':'GET',cache:'no-store',signal:AbortSignal.timeout(120000),headers:{'Content-Type':'application/json','X-Posting-Code':access.trim()},...(body?{body:JSON.stringify(body)}:{})});const result=await res.json().catch(()=>({error:'บริการตอบกลับไม่ถูกต้อง กรุณาเชื่อม Google Drive ใหม่'})) as {error?:string;rows:PostingRow[];row:PostingRow};if(res.status===401){setConnected(false);try{sessionStorage.removeItem('posting-access');}catch{}}if(!res.ok||result.error)throw Error(result.error||'บันทึกไม่สำเร็จ');return result;};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const connect=async(access=code)=>{const data=await api(undefined,access);if(!Array.isArray(data.rows))throw Error('บริการ Google Drive เดิมยังไม่ส่งข้อมูลทะเบียน กรุณาตรวจการตั้งค่า');setRows(data.rows);setConnected(true);try{sessionStorage.setItem('posting-access',access.trim());}catch{/* Central records remain usable when browser storage is blocked. */}setMessage(`อ่านข้อมูลจาก Master ใน Google Drive แล้ว ${data.rows.length} รายการ`);};
 useEffect(()=>{try{const access=sessionStorage.getItem('posting-access');if(access){setCode(access);void run(()=>connect(access));}}catch{setMessage('ใส่รหัสเข้าใช้งาน แล้วกดเชื่อม Google Drive ข้อมูลรายการเก็บใน Master เดิม');}},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(Object.keys(drafts).length||parts.length||photos.length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return ()=>window.removeEventListener('beforeunload',warn);},[drafts,parts,photos]);
 const combined=useMemo(()=>[...rows.map(r=>drafts[r.id]||r),...Object.values(drafts).filter(r=>!rows.some(x=>x.id===r.id))].sort((a,b)=>Number(b.revision===0)-Number(a.revision===0)||b.postedDate.localeCompare(a.postedDate)||b.sequence-a.sequence),[rows,drafts]);
 const visible=combined.filter(r=>(kind==='ทั้งหมด'||r.kind===kind)&&(!date||r.postedDate===date)&&(`${r.title} ${r.kind} ${r.postedDate}`).toLowerCase().includes(q.toLowerCase()));
 const edit=(r:PostingRow,patch:Partial<Draft>)=>setDrafts(prev=>({...prev,[r.id]:{...(prev[r.id]||r),...patch,requestId:undefined}}));
 const persist=async(d:Draft)=>{const requestId=d.requestId||crypto.randomUUID();setDrafts(prev=>({...prev,[d.id]:{...d,requestId}}));const body={...d,action:'save',requestId,pdfFile:undefined,photoFiles:undefined,pdfUpload:d.pdfFile?await uploadData(d.pdfFile,requestId):undefined,photoUploads:await Promise.all((d.photoFiles||[]).map((f,i)=>uploadData(f,requestId+'-'+i)))};const result=await api(body);setRows(prev=>[result.row,...prev.filter(r=>r.id!==d.id)]);setDrafts(prev=>{const next={...prev};delete next[d.id];return next;});return result.row as PostingRow;};
 const save=(d:Draft)=>run(async()=>{const match=d.revision===0?exactMatch(d.title,d.kind,d.postedDate,rows):undefined;if(match)throw Error('มีชื่อรายการนี้ในประเภทและวันที่เดียวกันแล้ว กรุณาแนบ PDF/รูปหรือแก้ไขที่รายการเดิม');await persist(d);setMessage('บันทึกและตรวจอ่านกลับจาก Master สำเร็จ');});
 const remove=(r:PostingRow)=>run(async()=>{if(!confirm('ลบรายการนี้จากทะเบียน? หลักฐานต้นฉบับยังเก็บใน Google Drive'))return;if(r.revision)await api({action:'delete',id:r.id,revision:r.revision,requestId:crypto.randomUUID()});setRows(prev=>prev.filter(x=>x.id!==r.id));setDrafts(prev=>{const next={...prev};delete next[r.id];return next;});setMessage('ลบรายการแล้ว');});
 const scanPdf=()=>run(async()=>{if(!pdf)throw Error('เลือก PDF ก่อน');const data=await readPdf(pdf,rows.filter(r=>r.postedDate===workDate),setMessage);setParts(data.parts.map(p=>({...p,id:crypto.randomUUID(),requestId:crypto.randomUUID()})));setTotal(data.total);setMessage('ตรวจช่วงหน้า ชื่อเรื่อง และรายการที่จับคู่ก่อนบันทึก ทุกประกาศอาจมีหลายหน้า');});
 const saveParts=()=>run(async()=>{if(!pdf)throw Error('เลือก PDF ก่อน');validateRanges(parts,total);if(parts.some(p=>!KINDS.includes(p.kind)))throw Error('เลือกประเภทให้ทุกชุดประกาศที่อ่านไม่มั่นใจ');if(parts.some(p=>!p.title.trim()))throw Error('ระบุชื่อทุกชุดประกาศ');const selected=parts.map(p=>p.target).filter(Boolean);if(new Set(selected).size!==selected.length)throw Error('เลือกจับคู่ PDF ได้หนึ่งชุดต่อรายการ');
  const latest=new Map(rows.map(r=>[r.id,r]));
  for(const p of parts){if(p.saved)continue;const existing=p.target?latest.get(p.target):exactMatch(p.title,p.kind,workDate,Array.from(latest.values()));if(p.target&&!existing)throw Error('ไม่พบรายการที่จับคู่ กรุณาโหลดข้อมูลใหม่');if(existing&&drafts[existing.id])throw Error('บันทึกการแก้ไขรายการก่อนแนบ PDF');if(existing?.pdf&&!confirm(`รายการ ${existing.title} มี PDF แล้ว ต้องการเปลี่ยนไฟล์ที่จับคู่หรือไม่? ไฟล์เดิมยังเก็บใน Drive`))throw Error('ยังไม่เปลี่ยน PDF');const d:Draft={...(existing||{...fresh(p.kind,workDate),id:p.id||crypto.randomUUID()}),requestId:p.requestId,title:p.title,kind:p.kind,pdfFile:await splitPdf(pdf,p.start,p.end,p.title)};const saved=await persist(d);latest.set(saved.id,saved);setParts(prev=>prev.map(x=>x===p?{...x,saved:true}:x));}setParts([]);setPdf(null);setMessage('แยก PDF และบันทึกทุกชุดลง Google Drive และ Master สำเร็จ');});
 const scanPhotos=(files:File[])=>run(async()=>{const found:Photo[]=[];let ocrAvailable=true;for(let i=0;i<files.length;i++){setMessage(`อ่านรูป ${i+1}/${files.length}`);let text='';if(ocrAvailable)try{text=await readImage(files[i]);}catch{ocrAvailable=false;/* Remaining images require manual pairing. */}found.push({file:files[i],text,target:suggest(text,rows.filter(r=>r.postedDate===workDate)),preview:URL.createObjectURL(files[i])});}setPhotos(prev=>[...prev,...found]);setMessage('ตรวจการจับคู่ รูปที่ไม่มั่นใจต้องเลือกเอง');});
 const savePhotos=()=>run(async()=>{if(photos.some(p=>!p.target))throw Error('เลือกจับคู่ทุกรูปก่อนบันทึก');if(photos.some(p=>drafts[p.target]))throw Error('บันทึกการแก้ไขรายการก่อนแนบรูป');for(const id of new Set(photos.map(p=>p.target))){const r=rows.find(r=>r.id===id);if(!r)throw Error('ไม่พบรายการ');await persist({...r,photoFiles:photos.filter(p=>p.target===id).map(p=>p.file)});setPhotos(prev=>prev.filter(p=>p.target!==id));}setMessage('เก็บรูปต้นฉบับและลิงก์ใน Master สำเร็จ');});
 const changePart=(i:number,patch:Partial<Part>)=>setParts(prev=>prev.map((x,j)=>j===i&&!x.saved?{...x,...patch,requestId:crypto.randomUUID()}:x));
 const movePhoto=(r:PostingRow,photoId:string,targetId:string)=>run(async()=>{if(!targetId)return;if(Object.keys(drafts).length)throw Error('บันทึกการแก้ไขรายการก่อนย้ายรูป');const target=rows.find(x=>x.id===targetId)!;await api({action:'movePhoto',id:r.id,revision:r.revision,photoId,targetId,targetRevision:target.revision,requestId:crypto.randomUUID()});await connect();setMessage('ย้ายการจับคู่รูปและบันทึก Master แล้ว');});
 const importLegacy=()=>run(async()=>{const legacy=await new Promise<Array<{id:number;title:string;kind:string;postedDate:string;pdf:File|null;photos:File[]}>>((ok,no)=>{const req=indexedDB.open('uttaradit-posting',1);req.onupgradeneeded=()=>req.result.createObjectStore('rows');req.onerror=()=>no(req.error);req.onsuccess=()=>{const db=req.result;const read=db.transaction('rows').objectStore('rows').get('current');read.onsuccess=()=>{ok(read.result||[]);db.close();};read.onerror=()=>no(read.error);};});for(const old of legacy){if(!old.title.trim())continue;const id='import-'+old.kind.length+'-'+old.id+'-'+old.postedDate; if(rows.some(r=>r.id===id))continue;const year=Number(old.postedDate.slice(0,4));const postedDate=(year>2400?String(year-543):old.postedDate.slice(0,4))+old.postedDate.slice(4);await persist({...fresh(old.kind,postedDate),id,title:old.title,pdfFile:old.pdf||undefined,photoFiles:old.photos});}setMessage('นำข้อมูลเดิมจากเครื่องนี้เข้า Master แล้ว ต้นฉบับในเครื่องยังอยู่');});
 return <main className="posting" style={{minHeight:'100vh',background:'linear-gradient(180deg,#eaf6ff,#fff)',color:'#16304f',fontFamily:'system-ui,sans-serif'}}>
 <style>{`.posting button,.posting input,.posting select{font:inherit;border:1px solid #b9cee5;border-radius:7px;padding:6px}.posting button{cursor:pointer;background:#eff6ff}.pos…1236 tokens truncated…||p.title,kind:rows.find(r=>r.id===e.target.value)?.kind||p.kind})}><option value="">สร้างรายการใหม่</option>{rows.map(r=><option key={r.id} value={r.id}>{r.postedDate} · {r.sequence} · {r.title}</option>)}</select><button onClick={()=>setParts(prev=>prev.filter((_,j)=>j!==i))}>ลบช่วง</button>{p.saved&&<b>บันทึกแล้ว</b>}</fieldset>)}<div className="tools" style={{marginTop:10}}><button onClick={()=>setParts(prev=>[...prev,{start:1,end:1,title:'',target:'',kind:activeKind,id:crypto.randomUUID(),requestId:crypto.randomUUID()}])}>เพิ่มช่วงประกาศ</button><button disabled={busy} onClick={saveParts}>ยืนยันและบันทึก PDF</button></div></section>}
 {photos.length>0&&<section style={card}><b>ตรวจการจับคู่ {photos.length} รูป</b>{photos.map((p,i)=><div key={p.preview} className="tools" style={{marginTop:8}}><a href={p.preview} target="_blank" rel="noreferrer"><img src={p.preview} alt={p.file.name} width={70}/></a><span>{p.file.name}</span><select aria-label={'จับคู่รูป '+p.file.name} value={p.target} onChange={e=>setPhotos(prev=>prev.map((x,j)=>j===i?{...x,target:e.target.value}:x))}><option value="">ไม่มั่นใจ — เลือกรายการเอง</option>{rows.map(r=><option key={r.id} value={r.id}>{r.postedDate} · {r.sequence} · {r.title}</option>)}</select><details><summary>ข้อความ OCR</summary>{p.text||'อ่านไม่ได้ กรุณาเลือกเอง'}</details><button onClick={()=>setPhotos(prev=>prev.filter((_,j)=>j!==i))}>นำออก</button></div>)}<button disabled={busy} onClick={savePhotos}>ยืนยันจับคู่และบันทึกรูป</button></section>}
 <div className="grid">{KINDS.map((k,i)=><button key={k} onClick={()=>setKind(k)} style={{...card,background:['#fff0f1','#f4efff','#edfbf4','#fff5e9'][i],textAlign:'left'}}><b>{['📣','📋','🏆','🚫'][i]} {k}</b><small>{rows.filter(r=>r.kind===k).length} รายการ</small></button>)}</div>
 <section style={card}><div className="tools"><input placeholder="🔎 ค้นหาชื่อรายการ วันที่ ประเภท" value={q} onChange={e=>setQ(e.target.value)} style={{flex:1,minWidth:220}}/><input aria-label="ค้นหาตามวันที่" type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option>ทั้งหมด</option>{KINDS.map(k=><option key={k}>{k}</option>)}</select><button onClick={()=>{setQ('');setDate('');setKind('ทั้งหมด');}}>ล้างค้นหา</button><button disabled={busy||!connected} onClick={()=>{const d=fresh(activeKind,workDate);setDrafts(prev=>({...prev,[d.id]:d}));}}>➕ เพิ่มรายการ</button></div></section>
 <section style={card}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:950}}><thead><tr>{['ลำดับ','ชื่อรายการ / ประเภท','วันที่ติดประกาศ','PDF','รูปหลักฐาน','บันทึก / ลบ'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.sequence||'ใหม่'}</td><td style={{minWidth:300}}><input aria-label="ชื่อรายการ" value={r.title} onChange={e=>edit(r,{title:e.target.value})} style={{width:'100%'}}/><select aria-label="ประเภทประกาศ" value={r.kind} onChange={e=>edit(r,{kind:e.target.value})} style={{width:'100%',fontSize:12,marginTop:3}}>{KINDS.map(k=><option key={k}>{k}</option>)}</select><details><summary style={{fontSize:12}}>หมายเหตุ / แก้หลักฐาน</summary><input placeholder="หมายเหตุ" value={r.notes} onChange={e=>edit(r,{notes:e.target.value})}/>{r.photos.map(p=><label key={p.id} style={{display:'block'}}><input type="checkbox" checked={!drafts[r.id]?.keepPhotoIds||drafts[r.id].keepPhotoIds!.includes(p.id)} onChange={e=>edit(r,{keepPhotoIds:e.target.checked?[...(drafts[r.id]?.keepPhotoIds||r.photos.map(x=>x.id)),p.id]:(drafts[r.id]?.keepPhotoIds||r.photos.map(x=>x.id)).filter(id=>id!==p.id)})}/>{p.name}<select aria-label="ย้ายรูปไปประกาศอื่น" defaultValue="" disabled={busy} onChange={e=>movePhoto(r,p.id,e.target.value)}><option value="">ย้ายรูปไปประกาศอื่น</option>{rows.filter(x=>x.id!==r.id).map(x=><option key={x.id} value={x.id}>{x.postedDate} · {x.title}</option>)}</select></label>)}</details></td><td><input type="date" value={r.postedDate} onChange={e=>edit(r,{postedDate:e.target.value})} style={{width:145}}/></td><td><label>📄 เพิ่ม/เปลี่ยน<input type="file" accept="application/pdf" style={{display:'block',width:155,fontSize:11}} disabled={busy} onChange={e=>edit(r,{pdfFile:e.target.files?.[0]})}/></label>{r.pdf&&<a href={r.pdf.url} target="_blank" rel="noreferrer">ดู / ดาวน์โหลด PDF</a>}{drafts[r.id]?.pdfFile&&<small>{drafts[r.id].pdfFile!.name}</small>}</td><td><input aria-label="เพิ่มรูป" type="file" multiple accept="image/*" style={{width:155,fontSize:11}} disabled={busy} onChange={e=>edit(r,{photoFiles:[...(drafts[r.id]?.photoFiles||[]),...Array.from(e.target.files||[])]})}/>{r.photos.map((p,i)=><a key={p.id||p.url} href={p.url} target="_blank" rel="noreferrer" style={{display:'block',fontSize:12}}>รูป {i+1} · ดู/ดาวน์โหลด</a>)}{drafts[r.id]?.photoFiles?.length&&<small>รอบันทึก {drafts[r.id].photoFiles!.length} รูป</small>}</td><td><button disabled={busy||!connected} onClick={()=>save(drafts[r.id]||r)}>💾 บันทึก</button><button disabled={busy} onClick={()=>remove(r)} aria-label="ลบรายการ">🗑️</button><small>{drafts[r.id]?'ยังไม่บันทึก':'บันทึกใน Master แล้ว'}</small></td></tr>)}</tbody></table>{visible.length===0&&<p>ยังไม่มีรายการที่ตรงกับเงื่อนไข</p>}</div></section>
 <small>ลำดับแยกตามประเภทและวันที่ รายการใหม่อยู่บนสุด เลขเดิมคงอยู่ การเปลี่ยนประเภทหรือวันจะได้รับเลขในกลุ่มใหม่ · กดบันทึกก่อนออกจากหน้า</small></div></main>;
}
